# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/ios/Meetup-Project
    
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    
    shell: /bin/bash --login -o pipefail
    
    steps:
      - checkout
      
      - run:
          name: post checkout check
          command: |
            echo $PWD
            cd ios/Meetup-Project
            echo $PWD
            ls -aslh .
      
#       - run:
#           name: Set Ruby Version
#           command:  echo "ruby-2.4" > ~/.ruby-version
      
#       - run: bundle install
      
#       - run:
#           name: Fastlane
#           command: bundle exec fastlane $FASTLANE_LANE
          
#       - run:
#           name: Fastlane
#           command: bundle exec fastlane
#       - store_artifacts:
#           path: output
#       - store_test_results:
#           path: output/scan
